version: '3'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MONGO_URI=mongodb://mongodb:27017/short-url
    ports:
      - "4001:4001"
    depends_on:
      - mongodb

volumes:
  mongodb_data: